In [ ]:
# Sam Brown
# sam_brown@mines.edu
# Jul 25
# Goal: Preprocess the position data so we can use the inter event movement as a feature for our models

import sys
sys.path.append("/Users/sambrown04/Documents/SURF/whillans-surf/notebooks/SURF")

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

import my_lib.funcs

In [11]:
# Want to get information about what happens in between events so we will load in the time frames for each event and what stations were operational.
df_2010 = my_lib.funcs.load_evt("/Users/sambrown04/Documents/SURF/Events/2010_2010Events2stas")
df_2011 = my_lib.funcs.load_evt("/Users/sambrown04/Documents/SURF/Events/2011_2011Events2stas")
df_2012 = my_lib.funcs.load_evt("/Users/sambrown04/Documents/SURF/Events/2012_2012Events2stas")
df_2013 = my_lib.funcs.load_evt("/Users/sambrown04/Documents/SURF/Events/2013_2013Events2stas")
df_2014 = my_lib.funcs.load_evt("/Users/sambrown04/Documents/SURF/Events/2014_2014Events2stas")
df_2015 = my_lib.funcs.load_evt("/Users/sambrown04/Documents/SURF/Events/2015_2015Events2stas")
df_2016 = my_lib.funcs.load_evt("/Users/sambrown04/Documents/SURF/Events/2016_2016Events2stas")
df_2017 = my_lib.funcs.load_evt("/Users/sambrown04/Documents/SURF/Events/2017_2017Events2stas")
df_2018 = my_lib.funcs.load_evt("/Users/sambrown04/Documents/SURF/Events/2018_2018Events2stas")
df_2019 = my_lib.funcs.load_evt("/Users/sambrown04/Documents/SURF/Events/2019_2019Events2stas")

# One Large list
all_dfs = (
    df_2010 + df_2011 + df_2012 + df_2013 +
    df_2014 + df_2015 + df_2016 + df_2017 + df_2018 + df_2019
)

In [22]:
all_dfs[-2].head()

,Unnamed: 0,time,la02x,la02y,la02z,la02res,la02res_avg,la08x,la08y,la08z,...,la18res,la18res_avg,gz20x,gz20y,gz20z,gz20res,gz20res_avg,sum_res_avg,ressum,event
0,1341281,2019-10-21 18:31:15,-275044.297195,-561767.734214,96.2830,0.51223,0.370092,-262960.996002,-519734.176054,95.2150,...,0.004409,0.012018,-154701.218959,-605733.211867,53.7134,0.003498,0.038585,0.554423,0.680393,1.0
1,1341282,2019-10-21 18:31:30,-275044.298839,-561767.738124,96.2882,0.51223,0.370092,-262960.996389,-519734.174503,95.2230,...,0.004409,0.012018,-154701.218859,-605733.209394,53.7303,0.003498,0.038585,0.554423,0.680393,1.0
2,1341283,2019-10-21 18:31:45,-275044.297655,-561767.734325,96.2857,0.51223,0.370092,-262960.995617,-519734.171165,95.2267,...,0.004409,0.012018,-154701.216714,-605733.206507,53.7201,0.003498,0.038585,0.554423,0.680393,1.0
3,1341284,2019-10-21 18:32:00,-275044.297434,-561767.734770,96.2876,0.51223,0.370092,-262960.995988,-519734.176400,95.2372,...,0.004409,0.012018,-154701.215924,-605733.207333,53.7215,0.003477,0.038585,0.554423,0.680363,1.0
4,1341285,2019-10-21 18:32:15,-275044.300255,-561767.731705,96.2763,0.51223,0.370092,-262961.001739,-519734.170440,95.2237,...,0.004409,0.012018,-154701.216381,-605733.201284,53.7146,0.003477,0.038585,0.554423,0.680312,1.0

In [30]:

dfs_sorted = sorted(all_dfs, key=lambda df: df['time'].iloc[0])

In [37]:
clean_df = my_lib.funcs.extract_event_features(dfs_sorted)

In [38]:
clean_df[0].head()

,station,pre-slip_area,slip_severity,peak_time,total_delta,start_time
0,la09x,13.285342,2.133253e-07,3420.0,0.091443,2010-01-01 15:25:30
1,slw1x,25.522392,1.232925e-06,3405.0,0.358676,2010-01-01 15:25:30

In [54]:
# Want to loop through and get the start_time end time for each event and the stations up during that time.
events_dict = []

for i, event in enumerate(dfs_sorted):
    start_time = event['time'].iloc[0]
    end_time = event['time'].iloc[-1]

    stations = clean_df[i]['station'].tolist()
    event = {
        'start_time': start_time,
        'end_time': end_time,
        'stations': stations
    }

    events_dict.append(event)

In [ ]:
# Now to get the inter event positional data we need to load in by year and station

input_dir = "/Users/sambrown04/Documents/SURF/POS Data"
dfs_by_year = {}

# loop over year folders
for year_folder in os.listdir(input_dir):
    year_path = os.path.join(input_dir, year_folder)

    year = int(year_folder)
    dfs_by_year[year] = []

    # loop over CSVs in that year folder
    for file in os.listdir(year_path):
        if file.endswith('.csv'):
            file_path = os.path.join(year_path, file)
            try:
                df = pd.read_csv(file_path)
                dfs_by_year[year].append(df)
            except Exception as e:
                print(f"Failed to load {file_path}: {e}")

In [ ]:
# For each event, have a dataframe that has the station as the columns and then a column for the datetime values